Revert "Try to diagnose [[trivially_relocatable]] on forward declarations."
This reverts commit c8f2501b7a870bfd46f44fbba832be957aadb61d.

It doesn't work because `isThisDeclarationADefinition` doesn't exist for
classes and class templates. :(

    lib/Sema/SemaDeclAttr.cpp:6087:11: error: no member named 'isThisDeclarationADefinition' in 'clang::Decl'; did
          you mean 'isThisDeclarationReferenced'?
      if (!D->isThisDeclarationADefinition()) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
              isThisDeclarationReferenced